columnDataTypes={'ID': int, 
    'Loan Amount': float, 
    'Funded Amount': float, 
    'Funded Amount Investor': float,
    'Term': int, 
    'Batch Enrolled': str,
    'Interest Rate': float,
    'Grade': str,
    'Sub Grade': str,
    'Employment Duration': str,
    'Home Ownership': float,
    'Verification Status': str,
    'Payment Plan': str,
    'Loan Title': str,
    'Debit to Income': float,
    'Delinquency - two years': int,
    'Inquires - six months': int,
    'Open Account': int,
    'Public Record': int,
    'Revolving Balance': float,
    'Revolving Utilities': float,
    'Total Accounts': int,
    'Initial List Status': str,
    'Total Received Interest': float,
    'Total Received Late Fee': float,
    'Recoveries': float,
    'Collection Recovery Fee': float,
    'Collection 12 months Medical': int,
    'Application Type': str,
    'Last week Pay': int,
    'Accounts Delinquent': int,
    'Total Collection Amount': float,
    'Total Current Balance': float,
    'Total Revolving Credit Limit': int,
    'Loan Status': bool
    }

columnNames=['ID', 'Loan Amount', 'Funded Amount', 'Funded Amount Investor', 'Term', 
    'Batch Enrolled', 'Interest Rate', 'Grade', 'Sub Grade', 'Employment Duration', 
    'Home Ownership', 'Verification Status', 'Payment Plan', 'Loan Title', 'Debit to Income', 
    'Delinquency - two years', 'Inquires - six months', 'Open Account', 'Public Record', 
    'Revolving Balance', 'Revolving Utilities', 'Total Accounts', 'Initial List Status', 
    'Total Received Interest', 'Total Received Late Fee', 'Recoveries', 'Collection Recovery Fee', 
    'Collection 12 months Medical', 'Application Type', 'Last week Pay', 'Accounts Delinquent', 
    'Total Collection Amount', 'Total Current Balance', 'Total Revolving Credit Limit', 
    'Loan Status']

categories=[
    'A','B','C','D','E','F','G',
    'A1','B1','C1','D1','E1','F1','G1',
    'A2','B2','C2','D2','E2','F2','G2',
    'A3','B3','C3','D3','E3','F3','G3',
    'A4','B4','C4','D4','E4','F4','G4',
    'A5','B5','C5','D5','E5','F5','G5',
    'RENT','OWN','MORTGAGE',
    'Source Verified','Verified','Not Verified',
    'Debt Consolidation', 'Debt consolidation',
    'Credit card refinancing', 'Home improvement',
    'Credit Consolidation', 'Green loan', 'Other',
    'Moving and relocation', 'Credit Cards', 'Medical expenses',
    'DEBT CONSOLIDATION', 'Home Improvement', 'Refinance',
    'credit card consolidation', 'Lending Club',
    'Debt Consolidation Loan', 'Major purchase', 'Vacation',
    'Business', 'Credit card payoff', 'Credit Card Consolidation',
    'credit card', 'Credit Card Refi', 'Personal Loan', 'CC Refi',
    'consolidate', 'Medical', 'Loan 1', 'Consolidation',
    'Card Consolidation', 'Car financing', 'debt', 'home improvement',
    'debt consolidation', 'Home buying', 'Freedom', 'Consolidate',
    'Consolidated', 'get out of debt', 'consolidation loan',
    'Dept consolidation', 'Personal loan', 'Personal', 'Debt', 'cards',
    'Cards', 'Bathroom', 'refi', 'Credit Card Loan',
    'Credit Card Debt', 'House', 'Debt Consolidation 2013',
    'debt loan', 'CC Refinance', 'Consolidation Loan', 'Home',
    'CC consolidation', 'Credit Card', 'Credit Card Refinance',
    'Credit Loan', 'payoff', 'Bill Consolidation',
    'credit card refinance', 'Credit Card consolidation',
    'Credit Card Paydown', 'Credit card pay off', 'vacation',
    'Credit card refinance', 'Get Debt Free', 'MYLOAN',
    'credit pay off', 'Payoff', 'consolidation', 'My Loan', 'Loan',
    'Bill Payoff', 'CC-Refinance', 'Debt Reduction', 'Medical loan',
    'Wedding Loan', 'Credit', 'CONSOLIDATE', 'personal',
    'pay off bills', 'CC Consolidation', 'Refinance Loan',
    'Credit Card Payoff', 'Debt Payoff', 'Car Loan', 'Pay Off',
    'Debt Loan', 'CONSOLIDATION', 'Pool', 'Credit payoff',
    'Credit Card Refinance Loan', 'CC Loan', 'Debt Free',
    'debt consolidation loan', 'conso', 'Home Improvement Loan',
    'Loan Consolidation', 'Debt payoff', 'Lending loan', 'relief',
    'CC', 'loan1', 'Getting Ahead', 'Home loan', 'bills',
    'n','t','f','w','y','INDIVIDUAL','JOINT']