columnDataTypes={'ID': int, 
    'Loan Amount': float, 
    'Funded Amount': float, 
    'Funded Amount Investor': float,
    'Term': int, 
    'Batch Enrolled': str,
    'Interest Rate': float,
    'Grade': str,
    'Sub Grade': str,
    'Employment Duration': str,
    'Home Ownership': float,
    'Verification Status': str,
    'Payment Plan': str,
    'Loan Title': str,
    'Debit to Income': float,
    'Delinquency - two years': int,
    'Inquires - six months': int,
    'Open Account': int,
    'Public Record': int,
    'Revolving Balance': float,
    'Revolving Utilities': float,
    'Total Accounts': int,
    'Initial List Status': str,
    'Total Received Interest': float,
    'Total Received Late Fee': float,
    'Recoveries': float,
    'Collection Recovery Fee': float,
    'Collection 12 months Medical': int,
    'Application Type': str,
    'Last week Pay': int,
    'Accounts Delinquent': int,
    'Total Collection Amount': float,
    'Total Current Balance': float,
    'Total Revolving Credit Limit': int,
    'Loan Status': bool
    }
columnNames=['ID', 'Loan Amount', 'Funded Amount', 'Funded Amount Investor', 'Term', 
    'Batch Enrolled', 'Interest Rate', 'Grade', 'Sub Grade', 'Employment Duration', 
    'Home Ownership', 'Verification Status', 'Payment Plan', 'Loan Title', 'Debit to Income', 
    'Delinquency - two years', 'Inquires - six months', 'Open Account', 'Public Record', 
    'Revolving Balance', 'Revolving Utilities', 'Total Accounts', 'Initial List Status', 
    'Total Received Interest', 'Total Received Late Fee', 'Recoveries', 'Collection Recovery Fee', 
    'Collection 12 months Medical', 'Application Type', 'Last week Pay', 'Accounts Delinquent', 
    'Total Collection Amount', 'Total Current Balance', 'Total Revolving Credit Limit', 
    'Loan Status']